/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#1a1c1c",
        "surface-container-low": "#f3f3f4",
        "tertiary-fixed-dim": "#cac6c4",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#474746",
        "tertiary": "#000000",
        "status-critical": "#D32F2F",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#868382",
        "surface-container-highest": "#e2e2e2",
        "inverse-primary": "#c8c6c5",
        "on-primary-container": "#858383",
        "inverse-on-surface": "#f0f1f1",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#1c1b1a",
        "secondary-container": "#dddddd",
        "outline": "#747878",
        "surface-variant": "#e2e2e2",
        "surface-container-high": "#e8e8e8",
        "status-healthy": "#2E7D32",
        "surface": "#ffffff",
        "inverse-surface": "#2f3131",
        "status-neutral": "#455A64",
        "on-secondary-fixed-variant": "#454747",
        "on-tertiary-fixed-variant": "#484645",
        "surface-dim": "#dadada",
        "primary-fixed": "#e5e2e1",
        "status-attention": "#F57C00",
        "secondary": "#5d5f5f",
        "secondary-fixed-dim": "#c6c6c6",
        "border-subtle": "#E5E5E5",
        "outline-variant": "#c4c7c7",
        "surface-bright": "#f9f9f9",
        "tertiary-fixed": "#e6e2df",
        "error-container": "#ffdad6",
        "on-surface": "#1a1c1c",
        "primary": "#000000",
        "primary-container": "#1c1b1b",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-tint": "#5f5e5e",
        "error": "#ba1a1a",
        "tertiary-container": "#1c1b1a",
        "on-secondary-fixed": "#1a1c1c",
        "primary-fixed-dim": "#c8c6c5",
        "background": "#f9f9f9",
        "on-secondary-container": "#606161",
        "on-surface-variant": "#444748",
        "surface-offset": "#FAFAFA",
        "on-primary-fixed": "#1c1b1b",
        "secondary-fixed": "#e2e2e2",
        "surface-container": "#eeeeee",
        "surface-container-lowest": "#ffffff"
      },
      borderRadius: {
        DEFAULT: "0px",
        none: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        full: "0px"
      },
      spacing: {
        "container-max": "1440px",
        gutter: "16px",
        margin: "24px",
        unit: "4px"
      },
      fontFamily: {
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "data-md": ["JetBrains Mono", "monospace"],
        "data-sm": ["JetBrains Mono", "monospace"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "data-lg": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["Hanken Grotesk", "sans-serif"]
      }
    }
  },
  plugins: [],
};
